### ISSUE TITLE
KeyError: 'defaultnamingcontext'

### ISSUE THREAD

**Issue by mpgn** [dirkjanm/ldapdomaindump#11]
Hello,
I just install the tool with pip but i keep getting this error : 

```
ldapdomaindump ldap://1.1.1.1:389                                      20:24:08
[*] Connecting as anonymous user, dumping will probably fail. Consider specifying a username/password to login with
[*] Connecting to host...
[*] Binding to host
[+] Bind OK
[*] Starting domain dump
Traceback (most recent call last):
  File "/home/bonclay/.local/bin/ldapdomaindump", line 3, in <module>
    ldapdomaindump.main()
  File "/home/bonclay/.local/lib/python2.7/site-packages/ldapdomaindump/__init__.py", line 892, in main
    dd = domainDumper(s, c, cnf)
  File "/home/bonclay/.local/lib/python2.7/site-packages/ldapdomaindump/__init__.py", line 158, in __init__
    self.root = self.getRoot()
  File "/home/bonclay/.local/lib/python2.7/site-packages/ldapdomaindump/__init__.py", line 171, in getRoot
    return self.server.info.other['defaultNamingContext'][0]
  File "/home/bonclay/.local/lib/python2.7/site-packages/ldap3/utils/ciDict.py", line 68, in __getitem__
    return self._store[self._case_insensitive_keymap[self._ci_key(key)]]
KeyError: 'defaultnamingcontext'
```

**Comment by dirkjanm** [comment]
Do you get the same error when you supply a username and password? And are you running this against an Active Directory LDAP server?

**Comment by mpgn** [comment]
my bad, I was using the wrong ldap server ^^ working fine now! thx

**Comment by n0skill** [comment]
@mpgn Could you tell us how did you solve it ? I still get the same error as @fasetto

**Comment by wh173n16h7** [comment]
me too.
