### ISSUE TITLE
Attribute value can be NoneType

### ISSUE THREAD

**Issue by iotmani** [dirkjanm/ldapdomaindump#15]
Hello,

Thanks for the great tool.
I've come across the following stack-trace, one or more attributes' value(s) appears to be NoneType:

```
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\lib\site-packages\ldapdomaindump\__main__.py", line 3, in <module>
    ldapdomaindump.main()
  File "C:\Program Files\Python37\lib\site-packages\ldapdomaindump\__init__.py", line 922, in main
    dd.domainDump()
  File "C:\Program Files\Python37\lib\site-packages\ldapdomaindump\__init__.py", line 414, in domainDump
    rw.generateUsersReport(self)
  File "C:\Program Files\Python37\lib\site-packages\ldapdomaindump\__init__.py", line 769, in generateUsersReport
    html = self.generateHtmlTable(dd.users, self.userattributes, 'Domain users')
  File "C:\Program Files\Python37\lib\site-packages\ldapdomaindump\__init__.py", line 503, in generateHtmlTable
    of.append('<td>%s</td>' % self.formatAttribute(li[att], liIsGroup))
  File "C:\Program Files\Python37\lib\site-packages\ldapdomaindump\__init__.py", line 591, in formatAttribute
    return ', '.join(self.parseFlags(att, uac_flags))
  File "C:\Program Files\Python37\lib\site-packages\ldapdomaindump\__init__.py", line 460, in parseFlags
    if attr.value & val:
TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'

```

FWIW, I was running in `-m` minimal mode due to a large set of data.

**Comment by dirkjanm** [comment]
Thanks for the fix!
