### ISSUE TITLE
Error with Domain Dump

### ISSUE THREAD

**Issue by rmdavy** [dirkjanm/ldapdomaindump#18]
Hi when I run the latest version I get this....

root@kali:/opt/ldapdomaindump# python ldapdomaindump.py -u "davy\rich" 192.168.226.10
Password: 
[*] Connecting to host...
[*] Binding to host
[+] Bind OK
[*] Starting domain dump
Traceback (most recent call last):
  File "ldapdomaindump.py", line 3, in <module>
    ldapdomaindump.main()
  File "/opt/ldapdomaindump/ldapdomaindump/__init__.py", line 922, in main
    dd.domainDump()
  File "/opt/ldapdomaindump/ldapdomaindump/__init__.py", line 411, in domainDump
    self.policy = self.getDomainPolicy()
  File "/opt/ldapdomaindump/ldapdomaindump/__init__.py", line 254, in getDomainPolicy
    self.connection.search(self.root, '(objectClass=domain)', attributes=ldap3.ALL_ATTRIBUTES)
  File "/usr/local/lib/python2.7/dist-packages/ldap3/core/connection.py", line 788, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
  File "/usr/local/lib/python2.7/dist-packages/ldap3/strategy/sync.py", line 139, in post_send_search
    responses, result = self.get_response(message_id)
  File "/usr/local/lib/python2.7/dist-packages/ldap3/strategy/base.py", line 325, in get_response
    responses = self._get_response(message_id)
  File "/usr/local/lib/python2.7/dist-packages/ldap3/strategy/sync.py", line 165, in _get_response
    dict_response = self.decode_response_fast(ldap_resp)
  File "/usr/local/lib/python2.7/dist-packages/ldap3/strategy/base.py", line 509, in decode_response_fast
    result = search_result_entry_response_to_dict_fast(ldap_message['payload'], self.connection.server.schema, self.connection.server.custom_formatter, self.connection.check_names)
  File "/usr/local/lib/python2.7/dist-packages/ldap3/operation/search.py", line 568, in search_result_entry_response_to_dict_fast
    entry_dict['attributes'] = checked_attributes_to_dict_fast(response[1][3], schema, custom_formatter)  # attributes
  File "/usr/local/lib/python2.7/dist-packages/ldap3/operation/search.py", line 453, in checked_attributes_to_dict_fast
    checked_attributes[name] = format_attribute_values(schema, name, decode_raw_vals_fast(attribute[3][1][3]) or [], custom_formatter)
  File "/usr/local/lib/python2.7/dist-packages/ldap3/protocol/formatters/standard.py", line 213, in format_attribute_values
    formatted_values = [formatter(raw_value) for raw_value in values]  # executes formatter
  File "/usr/local/lib/python2.7/dist-packages/ldap3/protocol/formatters/formatters.py", line 337, in format_ad_timedelta
    return format_ad_timestamp(raw_value * -1) - format_ad_timestamp(0)
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.datetime'

**Comment by dirkjanm** [comment]
Make sure you have ldap3 version 2.5.1, this looks like 2.5.2 which has a bug.

**Comment by rmdavy** [comment]
Thanks for the super quick reply - yes that does the trick.

**Comment by Lone-Wolf97** [comment]
hi hope everyones doing well im having this issue can anyone help
ldapdomaindump ldap://(ip) -u 'MARVEL\fcastle' -p Password1
[*] Connecting to host...
[*] Binding to host
Traceback (most recent call last):
  File "/usr/bin/ldapdomaindump", line 3, in <module>
    ldapdomaindump.main()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3/dist-packages/ldapdomaindump/__init__.py", line 934, in main
    if not c.bind():
           ~~~~~~^^
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 589, in bind
    self.open(read_server_info=False)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ldap3/strategy/sync.py", line 57, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ldap3/strategy/base.py", line 146, in open
    raise exception_history[0][0]
ldap3.core.exceptions.LDAPSocketOpenError: socket connection error while opening: [Errno 110] Connection timed out
