### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by pr0mming** [dirkjanm/ldapdomaindump#35]
Hi to all,

I have tried to extract information from a LDAP server, but in one part I receive this error in a group property, I am not sure what it is, has anyone else had a similar problem?

[*] Connecting as anonymous user, dumping will probably fail. Consider specifying a username/password to login with
[*] Connecting to host...
[*] Binding to host
[+] Bind OK
[*] Starting domain dump
Traceback (most recent call last):
  File "/root/Tools/ldapdomaindump/ldapdomaindump.py", line 3, in <module>
    ldapdomaindump.main()
  File "/root/Tools/ldapdomaindump/ldapdomaindump/__init__.py", line 950, in main
    dd.domainDump()
  File "/root/Tools/ldapdomaindump/ldapdomaindump/__init__.py", line 423, in domainDump
    rw.generateUsersReport(self)
  File "/root/Tools/ldapdomaindump/ldapdomaindump/__init__.py", line 795, in generateUsersReport
    dd.mapGroupsIdsToDns()
  File "/root/Tools/ldapdomaindump/ldapdomaindump/__init__.py", line 351, in mapGroupsIdsToDns
    gid = int(group.objectSid.value.split('-')[-1])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfb in position 13: ordinal not in range(128)

Thx

**Comment by dirkjanm** [comment]
This is the python3 equivalent of #26, which is likely caused by hackthebox doing some shady stuff which breaks ldapdomaindump
