### ISSUE TITLE
AttributeError: 'list' object has no attribute 'replace'

### ISSUE THREAD

**Issue by djackreuter** [dirkjanm/ldapdomaindump#48]
Hi, I am getting the following error. 
I am running ldapdomaindump in a Python 3.10.8 virtual environment. Installation was done with `python setup.py install` inside the virtual environment, and I used the following command (sensitive info replaced):
```
ldapdomaindump -u 'redacted.com\username' -p 'password' -d redacted.com -o loot ldaps://192.168.1.123
[*] Connecting to host...
[*] Binding to host
[+] Bind OK
[*] Starting domain dump
Traceback (most recent call last):
  File "/opt/ldapdomaindump/bin/ldapdomaindump", line 4, in <module>
    __import__('pkg_resources').run_script('ldapdomaindump==0.9.3', 'ldapdomaindump')
  File "/opt/ldapdomaindump/lib/python3.10/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/ldapdomaindump/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1472, in run_script
    exec(code, namespace, namespace)
  File "/opt/ldapdomaindump/lib/python3.10/site-packages/ldapdomaindump-0.9.3-py3.10.egg/EGG-INFO/scripts/ldapdomaindump", line 3, in <module>
    ldapdomaindump.main()
  File "/opt/ldapdomaindump/lib/python3.10/site-packages/ldapdomaindump-0.9.3-py3.10.egg/ldapdomaindump/__init__.py", line 946, in main
    dd.domainDump()
  File "/opt/ldapdomaindump/lib/python3.10/site-packages/ldapdomaindump-0.9.3-py3.10.egg/ldapdomaindump/__init__.py", line 424, in domainDump
    rw.generateUsersReport(self)
  File "/opt/ldapdomaindump/lib/python3.10/site-packages/ldapdomaindump-0.9.3-py3.10.egg/ldapdomaindump/__init__.py", line 793, in generateUsersReport
    html = self.generateHtmlTable(dd.users, self.userattributes, 'Domain users')
  File "/opt/ldapdomaindump/lib/python3.10/site-packages/ldapdomaindump-0.9.3-py3.10.egg/ldapdomaindump/__init__.py", line 521, in generateHtmlTable
    of.append('<td>%s</td>' % self.formatAttribute(li[att], liIsGroup))
  File "/opt/ldapdomaindump/lib/python3.10/site-packages/ldapdomaindump-0.9.3-py3.10.egg/ldapdomaindump/__init__.py", line 644, in formatAttribute
    return self.htmlescape(self.formatString(att.value))
  File "/opt/ldapdomaindump/lib/python3.10/site-packages/ldapdomaindump-0.9.3-py3.10.egg/ldapdomaindump/__init__.py", line 449, in htmlescape
    return (html.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("'", "&#39;").replace('"', "&quot;"))
AttributeError: 'list' object has no attribute 'replace'
```

Also tried with Python 3.9 and get the same error.

However, running the command on the latest Kali system installed ldapdomaindump shows the following, different error:
![image](https://user-images.githubusercontent.com/27731554/201975115-bf3efd7c-436f-45cf-ad91-73d5b2f82a72.png)

Thanks

**Comment by NeffIsBack** [comment]
Hi, we encountered your first error today and invested a little time in debugging the source of the problem. It seems to be, that in rare cases where there are newlines in combination with `,` in the ldap group description ldap3 interprets this as a list. Therefore there is no `replace` attribute on `list`. 
I am gonna submit a pull request to fix atleast the first error.

**Comment by dirkjanm** [comment]
This should be fixed in the latest release, let me know if further issues arise
