### ISSUE TITLE
  gid = int(group.objectSid.value.split('-')[-1]) TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by flashoop** [dirkjanm/ldapdomaindump#64]
python3 ldapdomaindump.py ldap://10.10.73.150

[*] Connecting as anonymous user, dumping will probably fail. Consider specifying a username/password to login with
[*] Connecting to host...
[*] Binding to host
[+] Bind OK
[*] Starting domain dump
Traceback (most recent call last):
  File "/home/kali/tools/ldap/ldapdomaindump/ldapdomaindump.py", line 3, in <module>
    ldapdomaindump.main()
  File "/home/kali/tools/ldap/ldapdomaindump/ldapdomaindump/__init__.py", line 956, in main
    dd.domainDump()
  File "/home/kali/tools/ldap/ldapdomaindump/ldapdomaindump/__init__.py", line 418, in domainDump
    rw.generateUsersReport(self)
  File "/home/kali/tools/ldap/ldapdomaindump/ldapdomaindump/__init__.py", line 801, in generateUsersReport
    dd.mapGroupsIdsToDns()
  File "/home/kali/tools/ldap/ldapdomaindump/ldapdomaindump/__init__.py", line 346, in mapGroupsIdsToDns
    gid = int(group.objectSid.value.split('-')[-1])
TypeError: a bytes-like object is required, not 'str'

**Comment by dirkjanm** [comment]
"Connecting as anonymous user, dumping will probably fail"

What scenario are you encountering that you expect anonymous enumeration to work? I'd need some more info to have a look at this issue. In a normal environment, anonymous enumeration will not work so an error is expected.

**Comment by pich4ya** [comment]
This occurs against HackTheBox Forest as well.
